language: node_js
node_js:
- '0.12'
sudo: false
after_success:
- gulp coverage
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    secure: MUSD1SVLfQcXILrDnCfPisvt9cT9IUWCvr/spGpIhutrA+yuh9Y15xTZVxF1VuErvrpSj6WtCxI36zxgsQdXSx1zQ+AoL6jliGO4rfb8Hd+E+s6Pim4hb78hPsIiOhzoexj0cWvvic21GXGSw0QeFo3qdid61tE4RuGs6VAk5xM=
  on:
    tags: true
